AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        # Laravel environment variables
        APP_STORAGE: '/tmp'

Resources:
  Website:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'area17-website'
      CodeUri: .
      Handler: public/index.php
      Timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
      Runtime: provided
      Layers:
        - 'arn:aws:lambda:us-east-1:209497400698:layer:php-72-fpm:4'
      Events:
        # The function will match all HTTP URLs
        HttpRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        HttpSubPaths:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
  Artisan:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'area17-artisan'
      CodeUri: .
      Handler: artisan
      Timeout: 120
      Runtime: provided
      Layers:
        # PHP runtime
        - 'arn:aws:lambda:us-east-1:209497400698:layer:php-72:4'
        # Console layer
        - 'arn:aws:lambda:us-east-1:209497400698:layer:console:4'

Outputs:
  DemoHttpApi:
    Description: 'URL of our function in the *Prod* environment'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
